/*!
 * This file is part of Visual S-Graphs (vS-Graphs).
 * Copyright (C) 2023-2025 SnT, University of Luxembourg
 *
 * 📝 Authors: Ali Tourani, Saad Ejaz, Hriday Bavle, Jose Luis Sanchez-Lopez,
 * and Holger Voos
 *
 * vS-Graphs is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This software is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details: https://www.gnu.org/licenses/
 */

/*!
 * @file            reasonCodeName.cc
 *
 * @brief           Implements reasonCodeName(), declared in EnumNames.h.
 */

#include "Semantic/SemanticAxiomEvaluator/EnumNames.h"

namespace vs_graphs
{
namespace core
{
namespace semantic
{

std::string reasonCodeName(ReasonCode reason_in)
{
    switch (reason_in)
    {
    case ReasonCode::FRAME_TRANSITION_EVALUATION_REQUIRED:
        return "FRAME_TRANSITION_EVALUATION_REQUIRED";
    case ReasonCode::FRAME_EQUIVARIANCE_NOT_YET_IMPLEMENTED:
        return "FRAME_EQUIVARIANCE_NOT_YET_IMPLEMENTED";
    case ReasonCode::WALL_OWNERSHIP_ZERO_OWNERS_COMMITMENT_UNVERIFIABLE:
        return "WALL_OWNERSHIP_ZERO_OWNERS_COMMITMENT_UNVERIFIABLE";
    case ReasonCode::WALL_OWNERSHIP_SINGLE_VALID_OWNER:
        return "WALL_OWNERSHIP_SINGLE_VALID_OWNER";
    case ReasonCode::WALL_OWNERSHIP_MULTIPLE_OWNERS:
        return "WALL_OWNERSHIP_MULTIPLE_OWNERS";
    case ReasonCode::WALL_OWNERSHIP_OWNER_BAD:
        return "WALL_OWNERSHIP_OWNER_BAD";
    case ReasonCode::WALL_OWNERSHIP_OWNER_UNRESOLVABLE:
        return "WALL_OWNERSHIP_OWNER_UNRESOLVABLE";
    case ReasonCode::WALL_OWNERSHIP_OWNER_CROSS_MAP:
        return "WALL_OWNERSHIP_OWNER_CROSS_MAP";
    case ReasonCode::WALL_OBSERVATION_RAY_EVIDENCE_UNAVAILABLE:
        return "WALL_OBSERVATION_RAY_EVIDENCE_UNAVAILABLE";
    case ReasonCode::WALL_TWIN_ABSENT:
        return "WALL_TWIN_ABSENT";
    case ReasonCode::WALL_TWIN_SELF:
        return "WALL_TWIN_SELF";
    case ReasonCode::WALL_TWIN_ASYMMETRIC:
        return "WALL_TWIN_ASYMMETRIC";
    case ReasonCode::WALL_TWIN_BAD:
        return "WALL_TWIN_BAD";
    case ReasonCode::WALL_TWIN_CROSS_MAP:
        return "WALL_TWIN_CROSS_MAP";
    case ReasonCode::WALL_TWIN_WRONG_TYPE:
        return "WALL_TWIN_WRONG_TYPE";
    case ReasonCode::WALL_TWIN_MAP_UNAVAILABLE:
        return "WALL_TWIN_MAP_UNAVAILABLE";
    case ReasonCode::WALL_TWIN_SHARED_OWNER_FORBIDDEN:
        return "WALL_TWIN_SHARED_OWNER_FORBIDDEN";
    case ReasonCode::WALL_TWIN_STRUCTURALLY_VALID_GEOMETRY_UNVERIFIED:
        return "WALL_TWIN_STRUCTURALLY_VALID_GEOMETRY_UNVERIFIED";
    case ReasonCode::PASSAGE_PROVENANCE_NOT_PASSABLE:
        return "PASSAGE_PROVENANCE_NOT_PASSABLE";
    case ReasonCode::PASSAGE_PROVENANCE_FULL_CHAIN_UNVERIFIABLE:
        return "PASSAGE_PROVENANCE_FULL_CHAIN_UNVERIFIABLE";
    case ReasonCode::PASSAGE_CARDINALITY_NO_CONFIRMED_ENDPOINT:
        return "PASSAGE_CARDINALITY_NO_CONFIRMED_ENDPOINT";
    case ReasonCode::PASSAGE_CARDINALITY_DUPLICATE_ENDPOINT:
        return "PASSAGE_CARDINALITY_DUPLICATE_ENDPOINT";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_BAD:
        return "PASSAGE_CARDINALITY_ENDPOINT_BAD";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_UNRESOLVABLE:
        return "PASSAGE_CARDINALITY_ENDPOINT_UNRESOLVABLE";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_CROSS_MAP:
        return "PASSAGE_CARDINALITY_ENDPOINT_CROSS_MAP";
    case ReasonCode::PASSAGE_CARDINALITY_NON_RECIPROCAL:
        return "PASSAGE_CARDINALITY_NON_RECIPROCAL";
    case ReasonCode::PASSAGE_CARDINALITY_VALID:
        return "PASSAGE_CARDINALITY_VALID";
    case ReasonCode::PASSAGE_SLOT_KNOWN_SIDE_NOT_CONFIRMED:
        return "PASSAGE_SLOT_KNOWN_SIDE_NOT_CONFIRMED";
    case ReasonCode::PASSAGE_SLOT_STATE_VALID:
        return "PASSAGE_SLOT_STATE_VALID";
    case ReasonCode::PASSAGE_FLOOR_ENDPOINT_CROSS_MAP:
        return "PASSAGE_FLOOR_ENDPOINT_CROSS_MAP";
    case ReasonCode::PASSAGE_FLOOR_DISAGREEMENT:
        return "PASSAGE_FLOOR_DISAGREEMENT";
    case ReasonCode::PASSAGE_FLOOR_EVIDENCE_UNAVAILABLE:
        return "PASSAGE_FLOOR_EVIDENCE_UNAVAILABLE";
    case ReasonCode::PASSAGE_FLOOR_AGREEMENT_VALID:
        return "PASSAGE_FLOOR_AGREEMENT_VALID";
    case ReasonCode::ROOM_CREATION_PROVENANCE_UNAVAILABLE:
        return "ROOM_CREATION_PROVENANCE_UNAVAILABLE";
    case ReasonCode::ROOM_FAR_SIDE_EVIDENCE_UNAVAILABLE:
        return "ROOM_FAR_SIDE_EVIDENCE_UNAVAILABLE";
    case ReasonCode::ROOM_BOUNDARY_TOO_FEW_CORNERS:
        return "ROOM_BOUNDARY_TOO_FEW_CORNERS";
    case ReasonCode::ROOM_BOUNDARY_DEGENERATE_EDGE:
        return "ROOM_BOUNDARY_DEGENERATE_EDGE";
    case ReasonCode::ROOM_BOUNDARY_SELF_INTERSECTING:
        return "ROOM_BOUNDARY_SELF_INTERSECTING";
    case ReasonCode::ROOM_BOUNDARY_NO_WALL_EVIDENCE:
        return "ROOM_BOUNDARY_NO_WALL_EVIDENCE";
    case ReasonCode::ROOM_BOUNDARY_CONFLICTING_STATE:
        return "ROOM_BOUNDARY_CONFLICTING_STATE";
    case ReasonCode::ROOM_BOUNDARY_GAP_CORRESPONDENCE_UNVERIFIED:
        return "ROOM_BOUNDARY_GAP_CORRESPONDENCE_UNVERIFIED";
    case ReasonCode::ROOM_BOUNDARY_NOT_YET_COMPLETE:
        return "ROOM_BOUNDARY_NOT_YET_COMPLETE";
    case ReasonCode::ROOM_BOUNDARY_STRUCTURALLY_VALID:
        return "ROOM_BOUNDARY_STRUCTURALLY_VALID";
    case ReasonCode::ROOM_FLOOR_UNLINKED:
        return "ROOM_FLOOR_UNLINKED";
    case ReasonCode::ROOM_FLOOR_NON_RECIPROCAL:
        return "ROOM_FLOOR_NON_RECIPROCAL";
    case ReasonCode::ROOM_FLOOR_CROSS_MAP:
        return "ROOM_FLOOR_CROSS_MAP";
    case ReasonCode::ROOM_FLOOR_RECIPROCAL_VALID:
        return "ROOM_FLOOR_RECIPROCAL_VALID";
    case ReasonCode::FLOOR_PASSAGE_CROSS_FLOOR:
        return "FLOOR_PASSAGE_CROSS_FLOOR";
    case ReasonCode::FLOOR_PASSAGE_EVIDENCE_UNAVAILABLE:
        return "FLOOR_PASSAGE_EVIDENCE_UNAVAILABLE";
    case ReasonCode::FLOOR_PASSAGE_AGREEMENT_VALID:
        return "FLOOR_PASSAGE_AGREEMENT_VALID";
    case ReasonCode::LIFECYCLE_QUARANTINE_PROVENANCE_UNAVAILABLE:
        return "LIFECYCLE_QUARANTINE_PROVENANCE_UNAVAILABLE";
    case ReasonCode::TRANSACTION_EVALUATION_REQUIRES_TRANSITION:
        return "TRANSACTION_EVALUATION_REQUIRES_TRANSITION";
    case ReasonCode::TRANSACTION_POSTCONDITION_NOT_YET_IMPLEMENTED:
        return "TRANSACTION_POSTCONDITION_NOT_YET_IMPLEMENTED";
    case ReasonCode::COMPLETENESS_ZERO_CONFIRMED_ROOMS:
        return "COMPLETENESS_ZERO_CONFIRMED_ROOMS";
    case ReasonCode::COMPLETENESS_LIVE_PROSPECTIVE_ROOM_PRESENT:
        return "COMPLETENESS_LIVE_PROSPECTIVE_ROOM_PRESENT";
    case ReasonCode::COMPLETENESS_ROOM_BOUNDARY_NOT_COMPLETE:
        return "COMPLETENESS_ROOM_BOUNDARY_NOT_COMPLETE";
    case ReasonCode::COMPLETENESS_PASSAGE_ENDPOINTS_INVALID:
        return "COMPLETENESS_PASSAGE_ENDPOINTS_INVALID";
    case ReasonCode::COMPLETENESS_HARD_CONTRADICTION:
        return "COMPLETENESS_HARD_CONTRADICTION";
    case ReasonCode::COMPLETENESS_EVIDENCE_UNAVAILABLE:
        return "COMPLETENESS_EVIDENCE_UNAVAILABLE";
    case ReasonCode::COMPLETENESS_NO_MAP_PRESENT:
        return "COMPLETENESS_NO_MAP_PRESENT";
    case ReasonCode::COMPLETENESS_ALL_CLEAR:
        return "COMPLETENESS_ALL_CLEAR";
    case ReasonCode::MERGE_PRESERVATION_NOT_YET_IMPLEMENTED:
        return "MERGE_PRESERVATION_NOT_YET_IMPLEMENTED";
    case ReasonCode::PASSAGE_CARDINALITY_THIRD_ENDPOINT:
        return "PASSAGE_CARDINALITY_THIRD_ENDPOINT";
    case ReasonCode::PASSAGE_CARDINALITY_REVERSE_ENDPOINT_BAD:
        return "PASSAGE_CARDINALITY_REVERSE_ENDPOINT_BAD";
    case ReasonCode::PASSAGE_CARDINALITY_REVERSE_ENDPOINT_CROSS_MAP:
        return "PASSAGE_CARDINALITY_REVERSE_ENDPOINT_CROSS_MAP";
    case ReasonCode::PASSAGE_CARDINALITY_ROOM_HAS_MALFORMED_REFERENCE:
        return "PASSAGE_CARDINALITY_ROOM_HAS_MALFORMED_REFERENCE";
    case ReasonCode::PASSAGE_CARDINALITY_DUPLICATE_ROOM_IDENTITY:
        return "PASSAGE_CARDINALITY_DUPLICATE_ROOM_IDENTITY";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_SLOT_UNVERIFIED:
        return "PASSAGE_CARDINALITY_ENDPOINT_SLOT_UNVERIFIED";
    case ReasonCode::WALL_OWNERSHIP_OWNER_LIVENESS_UNAVAILABLE:
        return "WALL_OWNERSHIP_OWNER_LIVENESS_UNAVAILABLE";
    case ReasonCode::WALL_OWNERSHIP_OWNER_WRONG_VARIANT:
        return "WALL_OWNERSHIP_OWNER_WRONG_VARIANT";
    case ReasonCode::WALL_OWNERSHIP_OWNER_DECLARED_MAP_MISMATCH:
        return "WALL_OWNERSHIP_OWNER_DECLARED_MAP_MISMATCH";
    case ReasonCode::WALL_OWNERSHIP_OWNER_NOT_RECIPROCAL:
        return "WALL_OWNERSHIP_OWNER_NOT_RECIPROCAL";
    case ReasonCode::WALL_OWNERSHIP_OWNER_DUPLICATE_IDENTITY:
        return "WALL_OWNERSHIP_OWNER_DUPLICATE_IDENTITY";
    case ReasonCode::WALL_OWNERSHIP_OWNER_RECORD_UNAVAILABLE:
        return "WALL_OWNERSHIP_OWNER_RECORD_UNAVAILABLE";
    case ReasonCode::ROOM_BOUNDARY_NON_FINITE_CORNER:
        return "ROOM_BOUNDARY_NON_FINITE_CORNER";
    case ReasonCode::ROOM_BOUNDARY_EDGE_SUPPORT_UNVERIFIED:
        return "ROOM_BOUNDARY_EDGE_SUPPORT_UNVERIFIED";
    case ReasonCode::ROOM_FLOOR_DUPLICATE_REVERSE_MEMBERSHIP:
        return "ROOM_FLOOR_DUPLICATE_REVERSE_MEMBERSHIP";
    case ReasonCode::ROOM_FLOOR_CLAIMED_BY_MULTIPLE_FLOORS:
        return "ROOM_FLOOR_CLAIMED_BY_MULTIPLE_FLOORS";
    case ReasonCode::ROOM_FLOOR_DUPLICATE_IDENTITY:
        return "ROOM_FLOOR_DUPLICATE_IDENTITY";
    case ReasonCode::COMPLETENESS_PASSAGE_SLOT_PROOF_UNAVAILABLE:
        return "COMPLETENESS_PASSAGE_SLOT_PROOF_UNAVAILABLE";
    case ReasonCode::PASSAGE_SLOT_ENDPOINT_PROOF_UNVERIFIED:
        return "PASSAGE_SLOT_ENDPOINT_PROOF_UNVERIFIED";
    case ReasonCode::PASSAGE_FLOOR_ENDPOINT_PROOF_UNVERIFIED:
        return "PASSAGE_FLOOR_ENDPOINT_PROOF_UNVERIFIED";
    case ReasonCode::FLOOR_PASSAGE_ENDPOINT_PROOF_UNVERIFIED:
        return "FLOOR_PASSAGE_ENDPOINT_PROOF_UNVERIFIED";
    case ReasonCode::PASSAGE_CARDINALITY_REVERSE_ENDPOINT_WRONG_KIND:
        return "PASSAGE_CARDINALITY_REVERSE_ENDPOINT_WRONG_KIND";
    case ReasonCode::PASSAGE_CARDINALITY_REVERSE_REFERENCE_DUPLICATED:
        return "PASSAGE_CARDINALITY_REVERSE_REFERENCE_DUPLICATED";
    case ReasonCode::PASSAGE_CARDINALITY_FORWARD_ENDPOINT_DUPLICATE_IDENTITY:
        return "PASSAGE_CARDINALITY_FORWARD_ENDPOINT_DUPLICATE_IDENTITY";
    case ReasonCode::WALL_OWNERSHIP_WALL_DUPLICATE_IDENTITY:
        return "WALL_OWNERSHIP_WALL_DUPLICATE_IDENTITY";
    case ReasonCode::WALL_OWNERSHIP_WALL_DECLARED_MAP_MISMATCH:
        return "WALL_OWNERSHIP_WALL_DECLARED_MAP_MISMATCH";
    case ReasonCode::WALL_OWNERSHIP_OWNER_RECORD_NOT_LIVE:
        return "WALL_OWNERSHIP_OWNER_RECORD_NOT_LIVE";
    case ReasonCode::ROOM_BOUNDARY_INVALID_WALL_EVIDENCE:
        return "ROOM_BOUNDARY_INVALID_WALL_EVIDENCE";
    case ReasonCode::ROOM_FLOOR_REVERSE_CLAIM_WITHOUT_FORWARD_LINK:
        return "ROOM_FLOOR_REVERSE_CLAIM_WITHOUT_FORWARD_LINK";
    case ReasonCode::ROOM_FLOOR_WRONG_KIND:
        return "ROOM_FLOOR_WRONG_KIND";
    case ReasonCode::ROOM_FLOOR_DECLARED_MAP_MISMATCH:
        return "ROOM_FLOOR_DECLARED_MAP_MISMATCH";
    case ReasonCode::PASSAGE_FLOOR_IDENTITY_AMBIGUOUS:
        return "PASSAGE_FLOOR_IDENTITY_AMBIGUOUS";
    case ReasonCode::FLOOR_PASSAGE_IDENTITY_AMBIGUOUS:
        return "FLOOR_PASSAGE_IDENTITY_AMBIGUOUS";
    case ReasonCode::COMPLETENESS_ROOM_CREATION_PROVENANCE_UNAVAILABLE:
        return "COMPLETENESS_ROOM_CREATION_PROVENANCE_UNAVAILABLE";
    case ReasonCode::COMPLETENESS_DUPLICATE_IDENTITY:
        return "COMPLETENESS_DUPLICATE_IDENTITY";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_WRONG_KIND:
        return "PASSAGE_CARDINALITY_ENDPOINT_WRONG_KIND";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_DECLARED_MAP_MISMATCH:
        return "PASSAGE_CARDINALITY_ENDPOINT_DECLARED_MAP_MISMATCH";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_LIVENESS_UNAVAILABLE:
        return "PASSAGE_CARDINALITY_ENDPOINT_LIVENESS_UNAVAILABLE";
    case ReasonCode::PASSAGE_CARDINALITY_REVERSE_ENDPOINT_LIVENESS_UNAVAILABLE:
        return "PASSAGE_CARDINALITY_REVERSE_ENDPOINT_LIVENESS_UNAVAILABLE";
    case ReasonCode::PASSAGE_SLOT_FORWARD_ENDPOINT_INVALID:
        return "PASSAGE_SLOT_FORWARD_ENDPOINT_INVALID";
    case ReasonCode::PASSAGE_FLOOR_FORWARD_ENDPOINT_INVALID:
        return "PASSAGE_FLOOR_FORWARD_ENDPOINT_INVALID";
    case ReasonCode::PASSAGE_FLOOR_ENDPOINT_ROOM_FLOOR_INVALID:
        return "PASSAGE_FLOOR_ENDPOINT_ROOM_FLOOR_INVALID";
    case ReasonCode::FLOOR_PASSAGE_FORWARD_ENDPOINT_INVALID:
        return "FLOOR_PASSAGE_FORWARD_ENDPOINT_INVALID";
    case ReasonCode::FLOOR_PASSAGE_ENDPOINT_ROOM_FLOOR_INVALID:
        return "FLOOR_PASSAGE_ENDPOINT_ROOM_FLOOR_INVALID";
    case ReasonCode::WALL_OWNERSHIP_WALL_WRONG_KEY_KIND:
        return "WALL_OWNERSHIP_WALL_WRONG_KEY_KIND";
    case ReasonCode::WALL_OWNERSHIP_WALL_WRONG_PLANE_TYPE:
        return "WALL_OWNERSHIP_WALL_WRONG_PLANE_TYPE";
    case ReasonCode::WALL_OWNERSHIP_OWNER_WRONG_KEY_KIND:
        return "WALL_OWNERSHIP_OWNER_WRONG_KEY_KIND";
    case ReasonCode::WALL_OWNERSHIP_WALL_DECLARED_MAP_UNAVAILABLE:
        return "WALL_OWNERSHIP_WALL_DECLARED_MAP_UNAVAILABLE";
    case ReasonCode::WALL_OWNERSHIP_RECIPROCAL_CONTRADICTORY:
        return "WALL_OWNERSHIP_RECIPROCAL_CONTRADICTORY";
    case ReasonCode::WALL_OWNERSHIP_RECIPROCAL_DUPLICATE:
        return "WALL_OWNERSHIP_RECIPROCAL_DUPLICATE";
    case ReasonCode::ROOM_BOUNDARY_WALL_EVIDENCE_UNAVAILABLE:
        return "ROOM_BOUNDARY_WALL_EVIDENCE_UNAVAILABLE";
    case ReasonCode::COMPLETENESS_DUPLICATE_MAP_IDENTITY:
        return "COMPLETENESS_DUPLICATE_MAP_IDENTITY";
    case ReasonCode::ROOM_FLOOR_ROOM_WRONG_KIND:
        return "ROOM_FLOOR_ROOM_WRONG_KIND";
    case ReasonCode::ROOM_FLOOR_ROOM_DECLARED_MAP_MISMATCH:
        return "ROOM_FLOOR_ROOM_DECLARED_MAP_MISMATCH";
    case ReasonCode::ROOM_FLOOR_ROOM_DECLARED_MAP_UNAVAILABLE:
        return "ROOM_FLOOR_ROOM_DECLARED_MAP_UNAVAILABLE";
    case ReasonCode::COMPLETENESS_ROOM_HAS_MALFORMED_PASSAGE_REFERENCE:
        return "COMPLETENESS_ROOM_HAS_MALFORMED_PASSAGE_REFERENCE";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_REASON_INCONSISTENT:
        return "PASSAGE_CARDINALITY_ENDPOINT_REASON_INCONSISTENT";
    case ReasonCode::PASSAGE_SLOT_ENDPOINT_CROSS_MAP:
        return "PASSAGE_SLOT_ENDPOINT_CROSS_MAP";
    case ReasonCode::FLOOR_PASSAGE_ENDPOINT_CROSS_MAP:
        return "FLOOR_PASSAGE_ENDPOINT_CROSS_MAP";
    case ReasonCode::ROOM_FLOOR_FLOOR_DECLARED_MAP_UNAVAILABLE:
        return "ROOM_FLOOR_FLOOR_DECLARED_MAP_UNAVAILABLE";
    case ReasonCode::ROOM_FLOOR_CONTAINING_MAP_AMBIGUOUS:
        return "ROOM_FLOOR_CONTAINING_MAP_AMBIGUOUS";
    case ReasonCode::ROOM_FLOOR_ROOM_REASON_INCONSISTENT:
        return "ROOM_FLOOR_ROOM_REASON_INCONSISTENT";
    case ReasonCode::ROOM_FLOOR_REVERSE_MEMBER_INVALID:
        return "ROOM_FLOOR_REVERSE_MEMBER_INVALID";
    case ReasonCode::ROOM_FLOOR_REVERSE_MEMBER_LIVENESS_UNAVAILABLE:
        return "ROOM_FLOOR_REVERSE_MEMBER_LIVENESS_UNAVAILABLE";
    case ReasonCode::PASSAGE_CARDINALITY_ENDPOINT_CONTAINING_MAP_AMBIGUOUS:
        return "PASSAGE_CARDINALITY_ENDPOINT_CONTAINING_MAP_AMBIGUOUS";
    case ReasonCode::WALL_OWNERSHIP_OWNER_REASON_INCONSISTENT:
        return "WALL_OWNERSHIP_OWNER_REASON_INCONSISTENT";
    case ReasonCode::WALL_OWNERSHIP_OWNER_CONTAINING_MAP_AMBIGUOUS:
        return "WALL_OWNERSHIP_OWNER_CONTAINING_MAP_AMBIGUOUS";
    case ReasonCode::WALL_OWNERSHIP_OWNER_DECLARED_MAP_UNAVAILABLE:
        return "WALL_OWNERSHIP_OWNER_DECLARED_MAP_UNAVAILABLE";
    case ReasonCode::WALL_TWIN_REASON_INCONSISTENT:
        return "WALL_TWIN_REASON_INCONSISTENT";
    case ReasonCode::WALL_TWIN_DUPLICATE_IDENTITY:
        return "WALL_TWIN_DUPLICATE_IDENTITY";
    case ReasonCode::WALL_TWIN_CONTAINING_MAP_AMBIGUOUS:
        return "WALL_TWIN_CONTAINING_MAP_AMBIGUOUS";
    case ReasonCode::PASSAGE_FLOOR_ENDPOINT_ROOM_FLOOR_UNVERIFIED:
        return "PASSAGE_FLOOR_ENDPOINT_ROOM_FLOOR_UNVERIFIED";
    case ReasonCode::FLOOR_PASSAGE_ENDPOINT_ROOM_FLOOR_UNVERIFIED:
        return "FLOOR_PASSAGE_ENDPOINT_ROOM_FLOOR_UNVERIFIED";
    }
    return "UNKNOWN_REASON_CODE";
}

} // namespace semantic
} // namespace core
} // namespace vs_graphs
