bool include_topology
---
bool available
string mode
float64 frame_timestamp
int32 tracking_state
int32 tracking_inliers
bool inertial
bool inertial_initialized
bool pose_valid
geometry_msgs/Pose pose
uint64 map_id
uint32 map_count
uint32 keyframe_count
uint64 reset_count
uint64 loop_event_sequence
uint32 accepted_loop_count
uint32 rejected_loop_count
bool has_loop_event
bool last_loop_accepted
uint64 last_loop_map_id
uint64 last_loop_current_keyframe_id
uint64 last_loop_matched_keyframe_id
float64 last_loop_current_timestamp
float64 last_loop_matched_timestamp
string last_loop_reason
uint32 confirmed_room_count
uint32 unresolved_room_count
int32 current_room_id
int32 last_known_room_id
uint32 floor_count
uint32 floor_room_link_count
uint32 passage_count
uint32 passable_passage_count
uint32 traversed_passage_count
uint32 bidirectional_passage_count
uint64 traversal_known_to_far_count
uint64 traversal_far_to_known_count
uint64 traversal_unknown_count
string topology_json
